name: LawerensCommons
version: '1.0'
main: com.lawerens.commons.LawerensCommons
api-version: '1.20'
depend:
  - LawerensCore
  - Essentials
  - Jobs
  - Vehicles
  - WorldGuard
commands:
  lrr:
  rr:
    aliases:
      - ruletarusa
      - russianrulette
  ldebug:
  bloodmoon: